<template>
  <div class="flex flex-col md-gap-y-4 items-center">
    <BsChip
      {$avatar}
      {$avatarCircle}
      {$avatarPadding}
      {$colorName}
      {$icon}
      {$iconAnimation}
      {$iconFlip}
      {$iconPosition}
      {$iconRotation}
      {$iconSize}
      {$iconSpin}
      {$shapes}
      {$sizes}
      {$states}
      {$variants}
      size="sm"
    >
      Chip Example
    </BsChip>
    <BsChip
      {$avatar}
      {$avatarCircle}
      {$avatarPadding}
      {$colorName}
      {$icon}
      {$iconAnimation}
      {$iconFlip}
      {$iconPosition}
      {$iconRotation}
      {$iconSize}
      {$iconSpin}
      {$shapes}
      {$sizes}
      {$states}
      {$variants}
    >
      Chip Example
    </BsChip>
    <BsChip
      {$avatar}
      {$avatarCircle}
      {$avatarPadding}
      {$colorName}
      {$icon}
      {$iconAnimation}
      {$iconFlip}
      {$iconPosition}
      {$iconRotation}
      {$iconSize}
      {$iconSpin}
      {$shapes}
      {$sizes}
      {$states}
      {$variants}
      size="lg"
    >
      Chip Example
    </BsChip>
  </div>
</template>
